# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 15:29
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('people', '0002_auto_20180201_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='partners.PartnerPage'),
        ),
    ]
