# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 15:37
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='people_covering', to='partners.PartnerPage'),
        ),
    ]
