# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180202_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True, verbose_name='Name of the skill')),
                ('level', models.IntegerField(null=True, verbose_name='from 0 to 100')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='intro_paragraph',
            field=models.CharField(blank=True, max_length=1022, verbose_name='Intro paragraph'),
        ),
        migrations.AddField(
            model_name='person',
            name='intro_subtitle',
            field=models.CharField(blank=True, max_length=254, verbose_name='Intro subtitle'),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=254, verbose_name='Linkedin link'),
        ),
        migrations.AddField(
            model_name='person',
            name='main_paragraph',
            field=models.CharField(blank=True, max_length=1022, verbose_name='Main paragraph'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(blank=True, max_length=254, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='skills', to='people.Skill'),
        ),
    ]
