# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180209_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=254, verbose_name='Linkedin link'),
        ),
    ]
