# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_person_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleindexpage',
            name='introduction_directors',
            field=models.TextField(blank=True, help_text='Text to describe the directors'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('D', 'Innovation Director'), ('T', 'Innovation Team'), ('A', 'Innovation Advisor')], max_length=1, verbose_name='Person type'),
        ),
    ]
